### ISSUE TITLE
Issue about githoney

### ISSUE THREAD

**Issue by FranZavalla** [NonOfficialGithoney/AGithoneyRepo#1]

**Comment by FranZavalla** [comment]
/githoney attach-bounty --amount 15 --address addr_test1qrvvmnvlv095al4mcp203d8m3e9sca7ttuyv8u0nmmzj9fprtgemhjhjt8te8lmnctvzss0e50njue595ntvfyn5503qujsqc3 --deadline 10

**Comment by Micrograx** [comment]
/githoney fund-bounty --tokens ADA=5 --address addr_test1qpkxq49y8vv5vwmacfs58h9dr6tzmdet8e4jvp5dkxxmaaqx69fzeuykylvmlcaav5eyp49stczujq0c2xxv83eukf5sc0ed6m
